### PR TITLE
Dynamic connectivity

### PR DESCRIPTION
**Pull request by adderan**

### CODE REVIEW

**Comment by benedictpaten** [comment]
Wow Alden, that's a lot of code! I was looking at the tests, do you have a random generator test? In such a test you generate a random graph and then track the connected components through a series of changes to the graph. At a random point you then stop, compute all the connected components with a stupid, simple algorithm and check the results are the same. I have always found the generator/stupid simple-algorithm check test pattern to be excellent for getting out bugs.

Also, have you run this all through valgrind or some program for catching memory corruption/leaks? I always find that is a useful process towards the end of large development cycle. 

As an aside, I have been making some figures for the paper. I will show you guys tomorrow.

**Comment by joelarmstrong** [comment]
The main connectivity implementation has a test (see https://github.com/benedictpaten/sonLib/pull/24/files#diff-9e489391c5f3aa5de0456d56244e15efR210 ) that compares a random graph against the naive version, which looks pretty solid to me.

Looks great, Alden! Thanks.

**Comment by joelarmstrong** [comment]
Merged this into the corresponding sonLib branch. BTW, Benedict, can you give Alden commit access to sonLib if he doesn't have it already?

**Comment by adderan** [comment]
I did forget to check for memory leaks after the most recent changes I made. I've just fixed them on my branch.

**Pull request merged**
